name: Test lib

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.x"

      - name: Install required packages
        run: |
          pip install -U pip
          pip install .
          pip install -r requirements.txt
          pip install -r dev_requirements.txt

      - name: Test
        working-directory: ./tests
        run: python3 test.py
